name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 建立环境
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: 构建
        run: mvn -B package --file pom.xml -DskipTests

      - name: 上传+JAR
        uses: actions/upload-artifact@v4
        with:
          name: project-jar
          path: target/result.jar
          retention-days: 30

      - name: 进行测试
        run: mvn test
        continue-on-error: true

      - name: 上传测试结果和保存测试结果
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure
          path: target/surefire-reports/
          retention-days: 30